---
Name: event-dispatcher-listeners-core
---
SilverStripe\Forms\GridField\GridField:
  extensions:
    - SilverStripe\CMSEvents\Listener\GridField\Alteration\GridFieldAlterationListenerExtension
    - SilverStripe\CMSEvents\Listener\GridField\Action\GridFieldActionListenerExtension

---
Name: event-dispatcher-listeners-form
Only:
  moduleexists: silverstripe/admin
---
SilverStripe\Forms\FormRequestHandler:
  extensions:
    - SilverStripe\CMSEvents\Listener\Form\FormListenerExtension


---
Name: event-dispatcher-listeners-cms
Only:
 moduleexists: silverstripe/cms
---
SilverStripe\CMS\Controllers\CMSMain:
  extensions:
    - SilverStripe\CMSEvents\Listener\CMSMain\CmsMainListenerExtension

