name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    # Do not run if this is a pull-request from same repo i.e. not a fork repo
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v2
